import { useState } from "react";
import { ChevronDown, HelpCircle } from "lucide-react";

const FAQS = [
  {
    q: "What types of synthetic media can DeepGuard detect?",
    a: "DeepGuard V10.0 OmniShield is trained to recognize portraits generated by StyleGAN, diffusion models (Midjourney, DALL-E, Stable Diffusion), and video face-swap tools by identifying synthetic boundary anomalies, generative smoothing, and frequency incoherence."
  },
  {
    q: "What is 3-Pass Test-Time Augmentation (TTA)?",
    a: "TTA runs multiple geometric transforms of the input image (canonical, horizontal reflection, and scale crops) through the neural network and pools predictions. This prevents false positives caused by unusual lighting, asymmetric angles, or compression artifacts."
  },
  {
    q: "Can this analysis be used as definitive legal evidence?",
    a: "DeepGuard AI is designed as a forensic decision-support tool for journalists, trust & safety teams, and identity verifiers. While its holdout accuracy exceeds 96%, automated systems should serve as forensic intelligence rather than a replacement for judicial verification."
  },
  {
    q: "Are my uploaded photos stored on the server?",
    a: "No. All images are processed strictly in-memory during inference and are immediately deallocated from RAM. No user photos are saved to persistent disks or shared with third parties."
  }
];

export default function FaqSection() {
  const [openIndex, setOpenIndex] = useState(null);

  const toggle = (idx) => {
    setOpenIndex(openIndex === idx ? null : idx);
  };

  return (
    <section id="faq" className="faq-section">
      <div className="section-container">
        <div className="section-header">
          <span className="section-kicker">FREQUENTLY ASKED QUESTIONS</span>
          <h2 className="section-title">Forensic Capabilities & Privacy</h2>
        </div>

        <div className="faq-grid">
          {FAQS.map((item, idx) => (
            <div
              key={item.q}
              className={`faq-card ${openIndex === idx ? "open" : ""}`}
              onClick={() => toggle(idx)}
            >
              <div className="faq-question-row">
                <span className="faq-question">{item.q}</span>
                <ChevronDown
                  size={16}
                  className={`faq-chevron ${openIndex === idx ? "rotated" : ""}`}
                />
              </div>
              {openIndex === idx && (
                <div className="faq-answer">
                  <p>{item.a}</p>
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
